const fontsArray = [
  ['white', 'Source Sans Pro'],
  ['white', 'Silkscreen'],
  ['white', 'Playfair Display'],
  ['white', 'ArimoRegular'],
  ['white', 'MistoBook'],
  ['white', 'FiraCodeRegular'],
  ['white', 'TomorrowRegular'],
  ['white', 'VG5000Regular'],
  ['white', 'MinipaxRegular'],
  ['white', 'KelvinchItalic'],
  //
  ['white', 'Source Sans Pro'],
  ['white', 'Silkscreen'],
  ['white', 'Playfair Display'],
  ['white', 'ArimoRegular'],
  ['white', 'MistoBook'],
  ['white', 'FiraCodeRegular'],
  ['white', 'TomorrowRegular'],
  ['white', 'VG5000Regular'],
  ['white', 'MinipaxRegular'],
  ['white', 'KelvinchItalic'],['white', 'Source Sans Pro'],
  ['white', 'Silkscreen'],
  ['white', 'Playfair Display'],
  ['white', 'ArimoRegular'],
  ['white', 'MistoBook'],
  ['white', 'FiraCodeRegular'],
  ['white', 'TomorrowRegular'],
  ['white', 'VG5000Regular'],
  ['white', 'MinipaxRegular'],
  ['white', 'KelvinchItalic'],['white', 'Source Sans Pro'],
  ['white', 'Silkscreen'],
  ['white', 'Playfair Display'],
  ['white', 'ArimoRegular'],
  ['white', 'MistoBook'],
  ['white', 'FiraCodeRegular'],
  ['white', 'TomorrowRegular'],
  ['white', 'VG5000Regular'],
  ['white', 'MinipaxRegular'],
  ['white', 'KelvinchItalic'],['white', 'Source Sans Pro'],
  ['white', 'Silkscreen'],
  ['white', 'Playfair Display'],
  ['white', 'ArimoRegular'],
  ['white', 'MistoBook'],
  ['white', 'FiraCodeRegular'],
  ['white', 'TomorrowRegular'],
  ['white', 'VG5000Regular'],
  ['white', 'MinipaxRegular'],
  ['white', 'KelvinchItalic'],['white', 'Source Sans Pro'],
  ['white', 'Silkscreen'],
  ['white', 'Playfair Display'],
  ['white', 'ArimoRegular'],
  ['white', 'MistoBook'],
  ['white', 'FiraCodeRegular'],
  ['white', 'TomorrowRegular'],
  ['white', 'VG5000Regular'],
  ['white', 'MinipaxRegular'],
  ['white', 'KelvinchItalic'],['white', 'Source Sans Pro'],
  ['white', 'Silkscreen'],
  ['white', 'Playfair Display'],
  ['white', 'ArimoRegular'],
  ['white', 'MistoBook'],
  ['white', 'FiraCodeRegular'],
  ['white', 'TomorrowRegular'],
  ['white', 'VG5000Regular'],
  ['white', 'MinipaxRegular'],
  ['white', 'KelvinchItalic'],['white', 'Source Sans Pro'],
  ['white', 'Silkscreen'],
  ['white', 'Playfair Display'],
  ['white', 'ArimoRegular'],
  ['white', 'MistoBook'],
  ['white', 'FiraCodeRegular'],
  ['white', 'TomorrowRegular'],
  ['white', 'VG5000Regular'],
  ['white', 'MinipaxRegular'],
  ['white', 'KelvinchItalic'],['white', 'Source Sans Pro'],
  ['white', 'Silkscreen'],
  ['white', 'Playfair Display'],
  ['white', 'ArimoRegular'],
  ['white', 'MistoBook'],
  ['white', 'FiraCodeRegular'],
  ['white', 'TomorrowRegular'],
  ['white', 'VG5000Regular'],
  ['white', 'MinipaxRegular'],
  ['white', 'KelvinchItalic'],['white', 'Source Sans Pro'],
  ['white', 'Silkscreen'],
  ['white', 'Playfair Display'],
  ['white', 'ArimoRegular'],
  ['white', 'MistoBook'],
  ['white', 'FiraCodeRegular'],
  ['white', 'TomorrowRegular'],
  ['white', 'VG5000Regular'],
  ['white', 'MinipaxRegular'],
  ['white', 'KelvinchItalic'],['white', 'Source Sans Pro'],
  ['white', 'Silkscreen'],
  ['white', 'Playfair Display'],
  ['white', 'ArimoRegular'],
  ['white', 'MistoBook'],
  ['white', 'FiraCodeRegular'],
  ['white', 'TomorrowRegular'],
  ['white', 'VG5000Regular'],
  ['white', 'MinipaxRegular'],
  ['white', 'KelvinchItalic'],['white', 'Source Sans Pro'],
  ['white', 'Silkscreen'],
  ['white', 'Playfair Display'],
  ['white', 'ArimoRegular'],
  ['white', 'MistoBook'],
  ['white', 'FiraCodeRegular'],
  ['white', 'TomorrowRegular'],
  ['white', 'VG5000Regular'],
  ['white', 'MinipaxRegular'],
  ['white', 'KelvinchItalic'],['white', 'Source Sans Pro'],
  ['white', 'Silkscreen'],
  ['white', 'Playfair Display'],
  ['white', 'ArimoRegular'],
  ['white', 'MistoBook'],
  ['white', 'FiraCodeRegular'],
  ['white', 'TomorrowRegular'],
  ['white', 'VG5000Regular'],
  ['white', 'MinipaxRegular'],
  ['white', 'KelvinchItalic'],['white', 'Source Sans Pro'],
  ['white', 'Silkscreen'],
  ['white', 'Playfair Display'],
  ['white', 'ArimoRegular'],
  ['white', 'MistoBook'],
  ['white', 'FiraCodeRegular'],
  ['white', 'TomorrowRegular'],
  ['white', 'VG5000Regular'],
  ['white', 'MinipaxRegular'],
  ['white', 'KelvinchItalic'],['white', 'Source Sans Pro'],
  ['white', 'Silkscreen'],
  ['white', 'Playfair Display'],
  ['white', 'ArimoRegular'],
  ['white', 'MistoBook'],
  ['white', 'FiraCodeRegular'],
  ['white', 'TomorrowRegular'],
  ['white', 'VG5000Regular'],
  ['white', 'MinipaxRegular'],
  ['white', 'KelvinchItalic'],['white', 'Source Sans Pro'],
  ['white', 'Silkscreen'],
  ['white', 'Playfair Display'],
  ['white', 'ArimoRegular'],
  ['white', 'MistoBook'],
  ['white', 'FiraCodeRegular'],
  ['white', 'TomorrowRegular'],
  ['white', 'VG5000Regular'],
  ['white', 'MinipaxRegular'],
  ['white', 'KelvinchItalic'],['white', 'Source Sans Pro'],
  ['white', 'Silkscreen'],
  ['white', 'Playfair Display'],
  ['white', 'ArimoRegular'],
  ['white', 'MistoBook'],
  ['white', 'FiraCodeRegular'],
  ['white', 'TomorrowRegular'],
  ['white', 'VG5000Regular'],
  ['white', 'MinipaxRegular'],
  ['white', 'KelvinchItalic'],['white', 'Source Sans Pro'],
  ['white', 'Silkscreen'],
  ['white', 'Playfair Display'],
  ['white', 'ArimoRegular'],
  ['white', 'MistoBook'],
  ['white', 'FiraCodeRegular'],
  ['white', 'TomorrowRegular'],
  ['white', 'VG5000Regular'],
  ['white', 'MinipaxRegular'],
  ['white', 'KelvinchItalic'],['white', 'Source Sans Pro'],
  ['white', 'Silkscreen'],
  ['white', 'Playfair Display'],
  ['white', 'ArimoRegular'],
  ['white', 'MistoBook'],
  ['white', 'FiraCodeRegular'],
  ['white', 'TomorrowRegular'],
  ['white', 'VG5000Regular'],
  ['white', 'MinipaxRegular'],
  ['white', 'KelvinchItalic'],['white', 'Source Sans Pro'],
  ['white', 'Silkscreen'],
  ['white', 'Playfair Display'],
  ['white', 'ArimoRegular'],
  ['white', 'MistoBook'],
  ['white', 'FiraCodeRegular'],
  ['white', 'TomorrowRegular'],
  ['white', 'VG5000Regular'],
  ['white', 'MinipaxRegular'],
  ['white', 'KelvinchItalic'],['white', 'Source Sans Pro'],
  ['white', 'Silkscreen'],
  ['white', 'Playfair Display'],
  ['white', 'ArimoRegular'],
  ['white', 'MistoBook'],
  ['white', 'FiraCodeRegular'],
  ['white', 'TomorrowRegular'],
  ['white', 'VG5000Regular'],
  ['white', 'MinipaxRegular'],
  ['white', 'KelvinchItalic'],['white', 'Source Sans Pro'],
  ['white', 'Silkscreen'],
  ['white', 'Playfair Display'],
  ['white', 'ArimoRegular'],
  ['white', 'MistoBook'],
  ['white', 'FiraCodeRegular'],
  ['white', 'TomorrowRegular'],
  ['white', 'VG5000Regular'],
  ['white', 'MinipaxRegular'],
  ['white', 'KelvinchItalic'],['white', 'Source Sans Pro'],
  ['white', 'Silkscreen'],
  ['white', 'Playfair Display'],
  ['white', 'ArimoRegular'],
  ['white', 'MistoBook'],
  ['white', 'FiraCodeRegular'],
  ['white', 'TomorrowRegular'],
  ['white', 'VG5000Regular'],
  ['white', 'MinipaxRegular'],
  ['white', 'KelvinchItalic'],['white', 'Source Sans Pro'],
  ['white', 'Silkscreen'],
  ['white', 'Playfair Display'],
  ['white', 'ArimoRegular'],
  ['white', 'MistoBook'],
  ['white', 'FiraCodeRegular'],
  ['white', 'TomorrowRegular'],
  ['white', 'VG5000Regular'],
  ['white', 'MinipaxRegular'],
  ['white', 'KelvinchItalic'],['white', 'Source Sans Pro'],
  ['white', 'Silkscreen'],
  ['white', 'Playfair Display'],
  ['white', 'ArimoRegular'],
  ['white', 'MistoBook'],
  ['white', 'FiraCodeRegular'],
  ['white', 'TomorrowRegular'],
  ['white', 'VG5000Regular'],
  ['white', 'MinipaxRegular'],
  ['white', 'KelvinchItalic'],['white', 'Source Sans Pro'],
  ['white', 'Silkscreen'],
  ['white', 'Playfair Display'],
  ['white', 'ArimoRegular'],
  ['white', 'MistoBook'],
  ['white', 'FiraCodeRegular'],
  ['white', 'TomorrowRegular'],
  ['white', 'VG5000Regular'],
  ['white', 'MinipaxRegular'],
  ['white', 'KelvinchItalic'],['white', 'Source Sans Pro'],
  ['white', 'Silkscreen'],
  ['white', 'Playfair Display'],
  ['white', 'ArimoRegular'],
  ['white', 'MistoBook'],
  ['white', 'FiraCodeRegular'],
  ['white', 'TomorrowRegular'],
  ['white', 'VG5000Regular'],
  ['white', 'MinipaxRegular'],
  ['white', 'KelvinchItalic'],['white', 'Source Sans Pro'],
  ['white', 'Silkscreen'],
  ['white', 'Playfair Display'],
  ['white', 'ArimoRegular'],
  ['white', 'MistoBook'],
  ['white', 'FiraCodeRegular'],
  ['white', 'TomorrowRegular'],
  ['white', 'VG5000Regular'],
  ['white', 'MinipaxRegular'],
  ['white', 'KelvinchItalic'],['white', 'Source Sans Pro'],
  ['white', 'Silkscreen'],
  ['white', 'Playfair Display'],
  ['white', 'ArimoRegular'],
  ['white', 'MistoBook'],
  ['white', 'FiraCodeRegular'],
  ['white', 'TomorrowRegular'],
  ['white', 'VG5000Regular'],
  ['white', 'MinipaxRegular'],
  ['white', 'KelvinchItalic'],['white', 'Source Sans Pro'],
  ['white', 'Silkscreen'],
  ['white', 'Playfair Display'],
  ['white', 'ArimoRegular'],
  ['white', 'MistoBook'],
  ['white', 'FiraCodeRegular'],
  ['white', 'TomorrowRegular'],
  ['white', 'VG5000Regular'],
  ['white', 'MinipaxRegular'],
  ['white', 'KelvinchItalic'],['white', 'Source Sans Pro'],
  ['white', 'Silkscreen'],
  ['white', 'Playfair Display'],
  ['white', 'ArimoRegular'],
  ['white', 'MistoBook'],
  ['white', 'FiraCodeRegular'],
  ['white', 'TomorrowRegular'],
  ['white', 'VG5000Regular'],
  ['white', 'MinipaxRegular'],
  ['white', 'KelvinchItalic'],['white', 'Source Sans Pro'],
  ['white', 'Silkscreen'],
  ['white', 'Playfair Display'],
  ['white', 'ArimoRegular'],
  ['white', 'MistoBook'],
  ['white', 'FiraCodeRegular'],
  ['white', 'TomorrowRegular'],
  ['white', 'VG5000Regular'],
  ['white', 'MinipaxRegular'],
  ['white', 'KelvinchItalic'],['white', 'Source Sans Pro'],
  ['white', 'Silkscreen'],
  ['white', 'Playfair Display'],
  ['white', 'ArimoRegular'],
  ['white', 'MistoBook'],
  ['white', 'FiraCodeRegular'],
  ['white', 'TomorrowRegular'],
  ['white', 'VG5000Regular'],
  ['white', 'MinipaxRegular'],
  ['white', 'KelvinchItalic'],['white', 'Source Sans Pro'],
  ['white', 'Silkscreen'],
  ['white', 'Playfair Display'],
  ['white', 'ArimoRegular'],
  ['white', 'MistoBook'],
  ['white', 'FiraCodeRegular'],
  ['white', 'TomorrowRegular'],
  ['white', 'VG5000Regular'],
  ['white', 'MinipaxRegular'],
  ['white', 'KelvinchItalic'],['white', 'Source Sans Pro'],
  ['white', 'Silkscreen'],
  ['white', 'Playfair Display'],
  ['white', 'ArimoRegular'],
  ['white', 'MistoBook'],
  ['white', 'FiraCodeRegular'],
  ['white', 'TomorrowRegular'],
  ['white', 'VG5000Regular'],
  ['white', 'MinipaxRegular'],
  ['white', 'KelvinchItalic'],['white', 'Source Sans Pro'],
  ['white', 'Silkscreen'],
  ['white', 'Playfair Display'],
  ['white', 'ArimoRegular'],
  ['white', 'MistoBook'],
  ['white', 'FiraCodeRegular'],
  ['white', 'TomorrowRegular'],
  ['white', 'VG5000Regular'],
  ['white', 'MinipaxRegular'],
  ['white', 'KelvinchItalic'],['white', 'Source Sans Pro'],
  ['white', 'Silkscreen'],
  ['white', 'Playfair Display'],
  ['white', 'ArimoRegular'],
  ['white', 'MistoBook'],
  ['white', 'FiraCodeRegular'],
  ['white', 'TomorrowRegular'],
  ['white', 'VG5000Regular'],
  ['white', 'MinipaxRegular'],
  ['white', 'KelvinchItalic'],['white', 'Source Sans Pro'],
  ['white', 'Silkscreen'],
  ['white', 'Playfair Display'],
  ['white', 'ArimoRegular'],
  ['white', 'MistoBook'],
  ['white', 'FiraCodeRegular'],
  ['white', 'TomorrowRegular'],
  ['white', 'VG5000Regular'],
  ['white', 'MinipaxRegular'],
  ['white', 'KelvinchItalic'],['white', 'Source Sans Pro'],
  ['white', 'Silkscreen'],
  ['white', 'Playfair Display'],
  ['white', 'ArimoRegular'],
  ['white', 'MistoBook'],
  ['white', 'FiraCodeRegular'],
  ['white', 'TomorrowRegular'],
  ['white', 'VG5000Regular'],
  ['white', 'MinipaxRegular'],
  ['white', 'KelvinchItalic'],['white', 'Source Sans Pro'],
  ['white', 'Silkscreen'],
  ['white', 'Playfair Display'],
  ['white', 'ArimoRegular'],
  ['white', 'MistoBook'],
  ['white', 'FiraCodeRegular'],
  ['white', 'TomorrowRegular'],
  ['white', 'VG5000Regular'],
  ['white', 'MinipaxRegular'],
  ['white', 'KelvinchItalic'],['white', 'Source Sans Pro'],
  ['white', 'Silkscreen'],
  ['white', 'Playfair Display'],
  ['white', 'ArimoRegular'],
  ['white', 'MistoBook'],
  ['white', 'FiraCodeRegular'],
  ['white', 'TomorrowRegular'],
  ['white', 'VG5000Regular'],
  ['white', 'MinipaxRegular'],
  ['white', 'KelvinchItalic'],['white', 'Source Sans Pro'],
  ['white', 'Silkscreen'],
  ['white', 'Playfair Display'],
  ['white', 'ArimoRegular'],
  ['white', 'MistoBook'],
  ['white', 'FiraCodeRegular'],
  ['white', 'TomorrowRegular'],
  ['white', 'VG5000Regular'],
  ['white', 'MinipaxRegular'],
  ['white', 'KelvinchItalic'],['white', 'Source Sans Pro'],
  ['white', 'Silkscreen'],
  ['white', 'Playfair Display'],
  ['white', 'ArimoRegular'],
  ['white', 'MistoBook'],
  ['white', 'FiraCodeRegular'],
  ['white', 'TomorrowRegular'],
  ['white', 'VG5000Regular'],
  ['white', 'MinipaxRegular'],
  ['white', 'KelvinchItalic'],['white', 'Source Sans Pro'],
  ['white', 'Silkscreen'],
  ['white', 'Playfair Display'],
  ['white', 'ArimoRegular'],
  ['white', 'MistoBook'],
  ['white', 'FiraCodeRegular'],
  ['white', 'TomorrowRegular'],
  ['white', 'VG5000Regular'],
  ['white', 'MinipaxRegular'],
  ['white', 'KelvinchItalic'],['white', 'Source Sans Pro'],
  ['white', 'Silkscreen'],
  ['white', 'Playfair Display'],
  ['white', 'ArimoRegular'],
  ['white', 'MistoBook'],
  ['white', 'FiraCodeRegular'],
  ['white', 'TomorrowRegular'],
  ['white', 'VG5000Regular'],
  ['white', 'MinipaxRegular'],
  ['white', 'KelvinchItalic'],['white', 'Source Sans Pro'],
  ['white', 'Silkscreen'],
  ['white', 'Playfair Display'],
  ['white', 'ArimoRegular'],
  ['white', 'MistoBook'],
  ['white', 'FiraCodeRegular'],
  ['white', 'TomorrowRegular'],
  ['white', 'VG5000Regular'],
  ['white', 'MinipaxRegular'],
  ['white', 'KelvinchItalic'],['white', 'Source Sans Pro'],
  ['white', 'Silkscreen'],
  ['white', 'Playfair Display'],
  ['white', 'ArimoRegular'],
  ['white', 'MistoBook'],
  ['white', 'FiraCodeRegular'],
  ['white', 'TomorrowRegular'],
  ['white', 'VG5000Regular'],
  ['white', 'MinipaxRegular'],
  ['white', 'KelvinchItalic'],['white', 'Source Sans Pro'],
  ['white', 'Silkscreen'],
  ['white', 'Playfair Display'],
  ['white', 'ArimoRegular'],
  ['white', 'MistoBook'],
  ['white', 'FiraCodeRegular'],
  ['white', 'TomorrowRegular'],
  ['white', 'VG5000Regular'],
  ['white', 'MinipaxRegular'],
  ['white', 'KelvinchItalic'],['white', 'Source Sans Pro'],
  ['white', 'Silkscreen'],
  ['white', 'Playfair Display'],
  ['white', 'ArimoRegular'],
  ['white', 'MistoBook'],
  ['white', 'FiraCodeRegular'],
  ['white', 'TomorrowRegular'],
  ['white', 'VG5000Regular'],
  ['white', 'MinipaxRegular'],
  ['white', 'KelvinchItalic'],['white', 'Source Sans Pro'],
  ['white', 'Silkscreen'],
  ['white', 'Playfair Display'],
  ['white', 'ArimoRegular'],
  ['white', 'MistoBook'],
  ['white', 'FiraCodeRegular'],
  ['white', 'TomorrowRegular'],
  ['white', 'VG5000Regular'],
  ['white', 'MinipaxRegular'],
  ['white', 'KelvinchItalic'],
]

let parent = document.querySelector('.parent');
console.log(parent);

let gigaTableau = parent.children;
console.log(gigaTableau);


const card = document.querySelector('.card_wrapper');
const card_verso_F = document.querySelector('.card_verso_F');
const btn = document.getElementById("card_close");

const modifyTypes = () => {
  for (var i = 0; i < gigaTableau.length; i++) {
    console.log(i);

    gigaTableau[i].style.backgroundColor = fontsArray[i][0];
    gigaTableau[i].style.fontFamily = fontsArray[i][1];
    gigaTableau[i].value = fontsArray[i][1];

    gigaTableau[i].addEventListener('click', function(){
      card.classList.remove('inactive');
      card_verso_F.style.fontFamily = this.value;
      console.log(this.value);

      btn.onclick = function () {
        if (card_verso_F.style.display !== "none") {
          card_verso_F.style.display = "none";
}
}
})
}
}
modifyTypes();
